### PR TITLE
fix vkd if res>=640

### PR DESCRIPTION
**Pull request by r-type**

### CODE REVIEW

**Comment by r-type** [comment]
BTW you last commit is nice ,now it works fine without an uaecfg file!

**Comment by Chips-fr** [comment]
I was getting lost between current & changed prefs but finally find a way to manage this. A .uea file will have higher priority than retroarch setting anyway (but i expect this is better this way).
I still have one issue i would like to do before pushing to libretro is following: a A1200 config from puae doesn't work correctly. I suspect a CPU speed issue (setting management of speed is not the same)

Adding
  finegrain_cpu_speed=1024 
make them works with right speed...

**Comment by r-type** [comment]
Just tested A1200 option , and it boot fine my hdf expect games not loading because of lack of extended memory. anyways it is a good start !
Another things that can be cool is not to move mouse when vkda is on 
https://github.com/Chips-fr/uae4arm-libretro/blob/master/libretro/core/core-mapper.cpp#L599
just adding a check to see if SHOWKEY==-1 should fix this case.
if(MOUSE_EMULATED==1 && SHOWKEY==-1 )

**Comment by r-type** [comment]
Ok i've modified in libretro-core.cpp and main.cpp to add 
some fastmem_size and gfxmem_size (accordind to my uaecgf) in A1200 conf
and now game load fine from my hdf with WHDLoad!

That isa very good thing that now we don"t have to deal with cfg file ! thanks

**Comment by Chips-fr** [comment]
Should be easy to add another options for fast mem (value up to 64MB was supported in this uae4arm) then we had zorro and gfx... but if i remember well fast mem should be enough for 99% of games & demos...

**Comment by Chips-fr** [comment]
well value above 8 doesn't seems to work
You can see my latest push, it has fastmem size option up to 8 MB.

**Pull request merged**
